### ISSUE TITLE
"Files on top" sorting isn't sticky

### ISSUE THREAD

**Issue by adamv** [ciaran/projectplus#27]
When TextMate reloads the project tree (due to files changing), it re-sorts the contents, ignoring the Project+ setting "Folders on top".

**Comment by danawoodman** [comment]
Yes, I have this issue as well. 

@ciaran Where is the code that handles the sorting? I'd be interested in checking out how to fix this issue as it is the main problem I've had with the plugin.

Is there an event that is fired when the project tree reloads? If so, could we attach the sorting method onto that event? Seems like it would be somewhat strait forward, no?

**Comment by sigerello** [comment]
Any progress with this issue since 2009?

**Comment by danawoodman** [comment]
Yeah, this would be VERY NICE to have fixed!
